### ISSUE TITLE
Inner Objekt Issue

### ISSUE THREAD

**Issue by Harlow-Seghorn** [Total-RP/Total-RP-3-Extended#169]
Sometimes inner objects can not be added with the use of workflows.
Instead of the inner item, which can be seen by an other player using the objectmanager, an missing class item is generated.

Thanks for your time

**Comment by Solanya** [comment]
If a missing class item is generated, the item you're generating is not an inner item. If your inner item was a copy of a separate item, make sure your effect has properly selected the inner item and not the source.
