### ISSUE TITLE
Spanish client Dice Roll workflow bug

### ISSUE THREAD

**Issue by Nitroso91** [Total-RP/Total-RP-3-Extended#180]
When you create a workflow using spanish interface (changed language and works correctly) and set a Dice Roll action, the workflow interface bugs and you cant keep editing that workflow since the i terface doesnt show the elements in the workflow

**Comment by Solanya** [comment]
There was indeed a typo in the translation provided on Curseforge for the dice roll preview. Typo has been fixed so the issue will be resolved on next update.
