### ISSUE TITLE
Macro in item is not running

### ISSUE THREAD

**Issue by Saliwan57140** [Total-RP/Total-RP-3-Extended#210]
I tried to create an item which run a macro on use. But when i use the item nothing happen.
Other instructions works without problem, but impossible to run a simple macro as /sit for exemple.

Here is an test item to reproduce :

!Lf17tnimm0)I0bLnDhFdlCN4Tv2iat)sq2wDhkc7a8h7l(3Ujf25PEuststE9LxrBmbv20YYzkQeiyBjUwyz7q73Tx(cQCOkGqfz7ri5bYNIbjNTPoTtZoqcBzSa9aGKx5Ee607ERvN)AXU2gekAp0nCmmPRShh(aAvv2DoKI2R7lkR6mihiZJd8Giv(spzC0y7)LLM2weYDeLEMyuQL(CkPpcIRNyBnri(6rHLRTJRTfb(n0Frv5hf1xC7PNlQqiJGFo1X)pzrenC1eK0EW9eRZgvna(n8c3ztDTCOXiJi6LZU0HzYTEdkOrrk7pTq)UUYmlPaoOOJ0g8i3eTrqGB42GvavP98RiXxYd)X2MNYp202xSTsBm566dL1ADBz9blcuzeUfbL3is8lefV2ZCJ0CtbB8yBgLIKczmh4Z3JG5(6aoMOgjeRmfMQyR0GZMaUPEZ1WsEiNC5gds(PMnEEyTjeHzFYoXKJ5Dsn9hzb)(

Sorry if i missed something but i made a lot of tests an never could run a macro.

**Comment by Solanya** [comment]
I'm aware of an issue with macro effects, will look to fix it soon.
