### ISSUE TITLE
No longer loads profiles from connected realms

### ISSUE THREAD

**Issue by EliHaser** [Total-RP/Total-RP-3-Extended#244]
As per the last TotalRP3 update, the addon can no longer load character profiles from connected realms, not even while in groups.

This issue has been noticed on connected realms such as Los Errantes, Colinas Pardas and Tyrande, as Los Errantes was the only RP realm in spain before it was connected to the other two, so the majority of Spain's RP community still plays there and in the other two realms.

The addon can still load profiles from other realms such as Argent Dawn while on instance groups, and still remembers profiles from characters on the other two connected realms, but can't update them or retrieve new ones.

Scan doesn't work either on said characters, only loading the main realm ones.

**Comment by Solanya** [comment]
This is a known issue from patch 10.2.6 and fully on Blizzard's side.
This might hopefully be fixed next patch.

**Comment by EliHaser** [comment]
Thanks for the reply, just wanted to make sure it was noted (or already known as you said!).
