### ISSUE TITLE
Add a delay before calling a workflow from a prompt

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3-Extended#65]
When using multiple prompts in a row, since there's only one prompt frame used, there might be an issue where the next prompt frame doesn't display properly, as the workflow is called right before the first prompt is closed.
To prevent that issue from happening, we could automatically add a small delay (~200 ms) before calling the workflow to let the prompt window close itself properly without impacting the flow too much.

**Comment by innuk** [comment]
Holy fricken spam.   47 messages and counting?
